version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'     # AMQP protocol
      - '15672:15672'   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - '3001:3001'
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '3002:3002'
    env_file:
      - ./user-service/.env
    depends_on:
      - mongodb

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    ports:
      - '3003:3003'
    env_file:
      - ./wallet-service/.env
    depends_on:
      - mongodb

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - '3004:3004'
    env_file:
      - ./transaction-service/.env
    depends_on:
      - mongodb
      - rabbitmq

  service-charge-service:
    build: ./service-charge-service
    container_name: service-charge-service
    ports:
      - '3005:3005'
    env_file:
      - ./service-charge-service/.env
    depends_on:
      - mongodb

  queue-service:
    build: ./queue-service
    container_name: queue-service
    depends_on:
      - rabbitmq
      - mongodb

  cron-service:
    build: ./cron-service
    container_name: cron-service
    depends_on:
      - mongodb

  dummy-bank-api:
    build: ./dummy-bank-api
    container_name: dummy-bank-api
    ports:
      - '3006:3006'

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - auth-service
      - user-service
      - wallet-service
      - transaction-service
      - service-charge-service

volumes:
  mongo-data:
